import { useEffect, useState } from 'react';
 import { Plus, Trash2, Archive, FileText, Sparkles } from 'lucide-react';
 import { Button } from '@/components/ui/button';
 import { Input } from '@/components/ui/input';
 import { Label } from '@/components/ui/label';
 import { Switch } from '@/components/ui/switch';
 import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
 import { 
   Select, 
   SelectContent, 
   SelectItem, 
   SelectTrigger, 
   SelectValue 
 } from '@/components/ui/select';
import { useAppStore } from '@/stores/appStore';
import { useToast } from '@/hooks/use-toast';
import { api } from '@/lib/api';
import { format } from 'date-fns';
import type { ContentIntent, Topic } from '@/types';
 
 export function TopicsView() {
   const { 
   topicQueue, 
   topicArchive, 
   topicAutoGenerate,
   contentIntentDefault,
    setTopicAutoGenerate,
    setTopicQueue,
    setTopicArchive
  } = useAppStore();
   const { toast } = useToast();
   
  const [newTopic, setNewTopic] = useState('');
  const [newIntent, setNewIntent] = useState<ContentIntent>(contentIntentDefault || 'informational');
  const [isGenerating, setIsGenerating] = useState(false);
  const [products, setProducts] = useState<any[]>([]);
  const [productId, setProductId] = useState('');
  const [productAngle, setProductAngle] = useState('');
  const [productPreview, setProductPreview] = useState('');
  const [productLoading, setProductLoading] = useState(false);

  useEffect(() => {
    if (contentIntentDefault) {
      setNewIntent(contentIntentDefault);
    }
  }, [contentIntentDefault]);

  useEffect(() => {
    (async () => {
      try {
        const res = await api.getShopifyProducts();
        if (res.connected) setProducts(res.products || []);
      } catch {
        // ignore
      }
    })();
  }, []);

  const refreshTopics = async () => {
    const updated = await api.getTopics();
    const updatedQueue: Topic[] = updated.topics.map((t: any, i: number) => ({
      id: `topic-${i}`,
      title: String(t?.title ?? t ?? ''),
      intent: (t?.intent || 'informational') as ContentIntent,
      createdAt: new Date(),
    }));
    const updatedArchive: Topic[] = (updated.archive || []).map((t: any, i: number) => ({
      id: String(t.articleId || `archive-${i}`),
      title: String(t.topic || t.title || ''),
      intent: (t.intent || 'informational') as ContentIntent,
      createdAt: new Date(t.postedAt || Date.now()),
      usedAt: t.postedAt ? new Date(t.postedAt) : undefined,
    }));
    setTopicQueue(updatedQueue);
    setTopicArchive(updatedArchive);
  };
   
  const handleAddTopic = async () => {
    if (!newTopic.trim()) {
      toast({
        title: "Topic required",
        description: "Please enter a topic title.",
        variant: "destructive",
      });
      return;
    }
    
    try {
      const cleaned = await api.cleanInput('topic', newTopic.trim(), 200);
      if (!cleaned.valid) {
        toast({
          title: "Invalid topic",
          description: cleaned.reason || "Please enter a valid topic.",
          variant: "destructive",
        });
        return;
      }
      const res = await api.addTopic(cleaned.cleaned, newIntent);
      const updatedQueue: Topic[] = res.topics.map((t: any, i: number) => ({
        id: `topic-${i}`,
        title: String(t?.title ?? t ?? ''),
        intent: (t?.intent || 'informational') as ContentIntent,
        createdAt: new Date(),
      }));
      setTopicQueue(updatedQueue);
      setNewTopic('');
      toast({
        title: "Topic added",
        description: `"${cleaned.cleaned}" added to queue.`,
      });
    } catch (e) {
      toast({
        title: "Add failed",
        description: String(e),
        variant: "destructive",
      });
    }
  };
  
  const handleRemoveTopic = async (index: number, title: string) => {
    try {
      const res = await api.removeTopic(index);
      const updatedQueue: Topic[] = res.topics.map((t: any, i: number) => ({
        id: `topic-${i}`,
        title: String(t?.title ?? t ?? ''),
        intent: (t?.intent || 'informational') as ContentIntent,
        createdAt: new Date(),
      }));
      setTopicQueue(updatedQueue);
      if ((res as any).autoGenerated > 0) {
        await refreshTopics();
        toast({
          title: "Topics generated",
          description: `Auto-generated ${(res as any).autoGenerated} topics.`,
        });
      }
      toast({
        title: "Topic removed",
        description: `"${title}" removed from queue.`,
      });
    } catch (e) {
      toast({
        title: "Remove failed",
        description: String(e),
        variant: "destructive",
      });
    }
  };
  
  const handleArchiveTopic = async (index: number, title: string) => {
    try {
      const res = await api.archiveTopic(index, title);
      const updatedQueue: Topic[] = res.topics.map((t: any, i: number) => ({
        id: `topic-${i}`,
        title: String(t?.title ?? t ?? ''),
        intent: (t?.intent || 'informational') as ContentIntent,
        createdAt: new Date(),
      }));
      const updatedArchive: Topic[] = res.archive.map((t: any, i: number) => ({
        id: String(t.articleId || `archive-${i}`),
        title: String(t.topic || t.title || ''),
        intent: (t.intent || 'informational') as ContentIntent,
        createdAt: new Date(t.postedAt || Date.now()),
        usedAt: t.postedAt ? new Date(t.postedAt) : undefined,
      }));
      setTopicQueue(updatedQueue);
      setTopicArchive(updatedArchive);
      if ((res as any).autoGenerated > 0) {
        await refreshTopics();
        toast({
          title: "Topics generated",
          description: `Auto-generated ${(res as any).autoGenerated} topics.`,
        });
      }
      toast({
        title: "Topic archived",
        description: `"${title}" moved to archive.`,
      });
    } catch (e) {
      toast({
        title: "Archive failed",
        description: String(e),
        variant: "destructive",
      });
    }
  };
   
   const getIntentBadge = (intent: ContentIntent) => {
     const styles = {
       informational: 'bg-brand/10 text-brand',
       commercial: 'bg-warning/10 text-warning',
       transactional: 'bg-success/10 text-success',
     };
     return (
       <span className={`text-2xs font-medium px-2 py-0.5 rounded-full ${styles[intent]}`}>
         {intent}
       </span>
     );
   };
   
   return (
     <div className="space-y-6 animate-fade-in">
       {/* Auto-generate controls */}
       <div className="panel">
         <div className="panel-body">
           <div className="flex items-center justify-between">
             <div className="flex items-center gap-3">
               <Sparkles className="w-5 h-5 text-brand" />
               <div>
                 <p className="text-sm font-medium">Auto-generate Topics</p>
                 <p className="text-xs text-muted-foreground">
                   Automatically generate new topics when queue is low
                 </p>
               </div>
             </div>
             <Switch
              checked={topicAutoGenerate}
              onCheckedChange={async () => {
                try {
                  const res = await api.toggleTopicGen();
                  setTopicAutoGenerate(!!res.enabled);
                  if ((res as any).autoGenerated > 0) {
                    await refreshTopics();
                    toast({
                      title: "Topics generated",
                      description: `Auto-generated ${(res as any).autoGenerated} topics.`,
                    });
                  }
                } catch (e) {
                  toast({
                    title: "Update failed",
                    description: String(e),
                    variant: "destructive",
                   });
                 }
               }}
             />
           </div>
         </div>
       </div>
       
       {/* Add Topic Form */}
       <div className="panel">
        <div className="panel-header flex items-center justify-between">
          <h2 className="font-semibold">Add Topic</h2>
          <Button
            size="sm"
            variant="outline"
            onClick={async () => {
              try {
                setIsGenerating(true);
                await api.generateTopics();
                await refreshTopics();
                toast({
                  title: "Topics generated",
                  description: "New topics were added.",
                });
              } catch (e) {
                toast({
                  title: "Generate failed",
                  description: String(e),
                  variant: "destructive",
                });
              } finally {
                setIsGenerating(false);
              }
            }}
            disabled={isGenerating}
          >
            <Sparkles className="w-4 h-4 mr-1" />
            {isGenerating ? 'Generating...' : 'Generate'}
          </Button>
        </div>
        <div className="panel-body">
          <div className="flex gap-3">
            <div className="flex-1">
              <Input
                placeholder="Enter a topic..."
                value={newTopic}
                onChange={(e) => setNewTopic(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleAddTopic()}
                onBlur={async () => {
                  if (!newTopic.trim()) return;
                  try {
                    const cleaned = await api.cleanInput('topic', newTopic.trim(), 200);
                    if (cleaned.valid) {
                      setNewTopic(cleaned.cleaned);
                    } else {
                      toast({
                        title: "Invalid topic",
                        description: cleaned.reason || "Please enter a valid topic.",
                        variant: "destructive",
                      });
                    }
                  } catch {
                    // ignore
                  }
                }}
              />
             </div>
             <Select value={newIntent} onValueChange={(v) => setNewIntent(v as ContentIntent)}>
               <SelectTrigger className="w-40">
                 <SelectValue />
               </SelectTrigger>
               <SelectContent>
                 <SelectItem value="informational">Informational</SelectItem>
                 <SelectItem value="commercial">Commercial</SelectItem>
                 <SelectItem value="transactional">Transactional</SelectItem>
               </SelectContent>
             </Select>
             <Button onClick={handleAddTopic}>
               <Plus className="w-4 h-4 mr-1" />
               Add
             </Button>
           </div>
         </div>
      </div>
      
      {/* Product-related post (manual) */}
      <div className="panel">
        <div className="panel-header">
          <h2 className="font-semibold">Product Post (Manual)</h2>
        </div>
        <div className="panel-body space-y-3">
          <p className="text-xs text-muted-foreground">
            Create a product-related post on demand. These are not auto-generated.
          </p>
          <div className="grid gap-3 md:grid-cols-3">
            <div className="md:col-span-1">
              <Label className="text-xs">Product</Label>
              <Select value={productId} onValueChange={setProductId}>
                <SelectTrigger>
                  <SelectValue placeholder="Select a product" />
                </SelectTrigger>
                <SelectContent>
                  {products.map((p) => (
                    <SelectItem key={p.id} value={p.id}>
                      {p.title}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="md:col-span-2">
              <Label className="text-xs">Angle (optional)</Label>
              <Input
                placeholder="e.g., benefits, use cases, comparison, seasonal"
                value={productAngle}
                onChange={(e) => setProductAngle(e.target.value)}
              />
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              disabled={!productId || productLoading}
              onClick={async () => {
                try {
                  setProductLoading(true);
                  const res = await api.productPostPreview(productId, productAngle.trim() || undefined);
                  setProductPreview(res.content || '');
                } catch (e) {
                  toast({
                    title: "Preview failed",
                    description: String(e),
                    variant: "destructive",
                  });
                } finally {
                  setProductLoading(false);
                }
              }}
            >
              {productLoading ? 'Generating...' : 'Generate Preview'}
            </Button>
            <Button
              size="sm"
              disabled={!productId || productLoading}
              onClick={async () => {
                try {
                  setProductLoading(true);
                  const res = await api.productPostPublish(productId, productAngle.trim() || undefined, 'live');
                  toast({
                    title: "Product post published",
                    description: res.isPublished ? "Live in Shopify." : "Created as draft.",
                  });
                } catch (e) {
                  toast({
                    title: "Publish failed",
                    description: String(e),
                    variant: "destructive",
                  });
                } finally {
                  setProductLoading(false);
                }
              }}
            >
              Publish Now
            </Button>
          </div>
          {productPreview && (
            <div className="rounded-md border border-border bg-muted/20 p-3 max-h-56 overflow-y-auto text-sm whitespace-pre-wrap">
              {productPreview}
            </div>
          )}
        </div>
      </div>

      {/* Topics Tabs */}
       <Tabs defaultValue="queue" className="space-y-4">
         <TabsList>
           <TabsTrigger value="queue">
             Queue ({topicQueue.length})
           </TabsTrigger>
           <TabsTrigger value="archive">
             Archive ({topicArchive.length})
           </TabsTrigger>
         </TabsList>
         
         <TabsContent value="queue">
           {topicQueue.length > 0 ? (
             <div className="panel">
               <div className="divide-y divide-border">
                {topicQueue.map((topic, index) => (
                  <div key={topic.id} className="flex items-center gap-4 px-5 py-4">
                    <FileText className="w-4 h-4 text-muted-foreground flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">{topic.title}</p>
                       <p className="text-xs text-muted-foreground">
                         Added {format(new Date(topic.createdAt), 'MMM d, yyyy')}
                       </p>
                     </div>
                    {getIntentBadge(topic.intent)}
                    <div className="flex items-center gap-1">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleArchiveTopic(index, topic.title)}
                        className="text-muted-foreground hover:text-foreground"
                      >
                        <Archive className="w-4 h-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleRemoveTopic(index, topic.title)}
                        className="text-muted-foreground hover:text-destructive"
                      >
                        <Trash2 className="w-4 h-4" />
                       </Button>
                     </div>
                   </div>
                 ))}
               </div>
             </div>
           ) : (
             <div className="panel">
               <div className="panel-body text-center py-12">
                 <FileText className="w-10 h-10 text-muted-foreground mx-auto mb-3" />
                 <p className="text-muted-foreground">No topics in queue</p>
                 <p className="text-sm text-muted-foreground mt-1">
                   Add topics above or enable auto-generation
                 </p>
               </div>
             </div>
           )}
         </TabsContent>
         
        <TabsContent value="archive">
          <div className="flex items-center justify-end gap-2 mb-3">
            <Button
              variant="outline"
              size="sm"
              onClick={async () => {
                try {
                  const res = await api.releaseTopicArchive();
                  const updatedQueue: Topic[] = res.topics.map((t: any, i: number) => ({
                    id: `topic-${i}`,
                    title: String(t?.title ?? t ?? ''),
                    intent: (t?.intent || 'informational') as ContentIntent,
                    createdAt: new Date(),
                  }));
                  setTopicQueue(updatedQueue);
                  setTopicArchive([]);
                  toast({
                    title: "Archive released",
                    description: "Archived topics were returned to the queue.",
                  });
                } catch (e) {
                  toast({
                    title: "Release failed",
                    description: String(e),
                    variant: "destructive",
                  });
                }
              }}
            >
              Release Archive to Queue
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={async () => {
                try {
                  await api.clearTopicArchive();
                  setTopicArchive([]);
                  toast({
                    title: "Archive cleared",
                    description: "Archived topics were removed.",
                  });
                } catch (e) {
                  toast({
                    title: "Clear failed",
                    description: String(e),
                    variant: "destructive",
                  });
                }
              }}
            >
              Clear Archive
            </Button>
          </div>
          {topicArchive.length > 0 ? (
            <div className="panel">
               <div className="divide-y divide-border">
                 {topicArchive.map((topic) => (
                   <div key={topic.id} className="flex items-center gap-4 px-5 py-4 opacity-60">
                     <FileText className="w-4 h-4 text-muted-foreground flex-shrink-0" />
                     <div className="flex-1 min-w-0">
                       <p className="text-sm font-medium truncate">{topic.title}</p>
                       <p className="text-xs text-muted-foreground">
                         Used {topic.usedAt ? format(new Date(topic.usedAt), 'MMM d, yyyy') : 'N/A'}
                       </p>
                     </div>
                     {getIntentBadge(topic.intent)}
                   </div>
                 ))}
               </div>
             </div>
           ) : (
             <div className="panel">
               <div className="panel-body text-center py-12">
                 <Archive className="w-10 h-10 text-muted-foreground mx-auto mb-3" />
                 <p className="text-muted-foreground">No archived topics</p>
                 <p className="text-sm text-muted-foreground mt-1">
                   Used topics will appear here
                 </p>
               </div>
             </div>
           )}
         </TabsContent>
       </Tabs>
     </div>
   );
 }
